[pytest]
asyncio_mode = auto
testpaths = src/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
env =
    DATABASE_URL=postgresql+asyncpg://gymblubbot:verystrongpassword@db:5432/gymbot_db_test
    ADMIN_TELEGRAM_ID=121231231
    ADMIN_API_KEY=test-admin-key
    TELEGRAM_BOT_TOKEN=test-token